# ver 20250322143730.1
[build]
  publish = "./"
  command = "echo 'No build needed'"

[context.production.environment]
  NODE_VERSION = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
